
from typing import Any

async def fetch(url: str) -> Any: ...
async def download(url: str, path: str) -> Any: ...
async def resolve_dns(domain: str) -> Any: ...
async def ping(host: str) -> Any: ...
async def write_text(path: str, content: str) -> Any: ...
async def read_text(path: str) -> Any: ...
def hash_256(input: str) -> str: ...
def uuid() -> str: ...
def encode_base64(input: str) -> str: ...
def decode_base64(input: str) -> str: ...
async def sleep(seconds: int) -> None: ...
def now() -> Any: ...
def get_platform() -> str: ...
async def run(cmd: str) -> Any: ...
def mem_usage() -> Any: ...